# Defaults tasks for role fedmsg
---
- name: Install fedmsg packages packages
  yum:
    name:
      - python3-fedmsg
      - python3-psutil
      - python3-moksha-hub
      - python3-click
      - python3-pygments
    state: present

- name: Ensure group "fedmsg" exists
  group:
    name: fedmsg
    state: present
  
- name: Ensure user "fedmsg" exists
  user:
    name: fedmsg
    comment: fedmsg
    group: fedmsg
  
- name: Ensure /etc/fedmsg.d/ folder exists
  file:
    path: /etc/fedmsg.d/
    state: directory
    owner: root
    group: fedmsg
    mode: 0755
  
- name: setup basic /etc/fedmsg.d/ contents for internal hosts
  template:
    src: "base/{{ item }}.j2"
    dest: "/etc/fedmsg.d/{{ item }}"
    owner: root
    group: fedmsg
    mode: 0644
  with_items:
    - logging.py
    - base.py
  notify:
    - Reload apache
    - Restart fedmsg-hub
  
- name: Enable the websocket server if we should
  template:
    src: websocket.py.j2
    dest: /etc/fedmsg.d/websocket.py
  when: fedmsg_enable_websocket_server
  notify:
    - Restart fedmsg-hub
  
- name: Disable the websocket server if we should..
  file:
    path: /etc/fedmsg.d/websocket.py
    state: absent
  when: not fedmsg_enable_websocket_server
  notify:
    - Restart fedmsg-hub
  
- name: Create systemd config directory
  file:
    path: /etc/systemd/system/fedmsg-hub.service.d
    state: directory
  notify:
    - Reload systemd

- name: Install systemd config file
  template:
    src: fedmsg-hub-systemd.conf.j2
    dest: /etc/systemd/system/fedmsg-hub.service.d/systemd.conf
  notify:
    - Reload systemd
    - Restart fedmsg-hub

- name: Create fedmsg-hub systemd file
  template:
    src: fedmsg-hub.service.j2
    dest: /usr/lib/systemd/system/fedmsg-hub.service
  
- name: Fedmsg-hub service
  systemd:
    name: fedmsg-hub
    state: started
    enabled: yes
    daemon_reload: yes
  